### ISSUE TITLE
Fails to run in Windows

### ISSUE THREAD

**Issue by w1nsid** [iordic/jdcx#2]
Hello first i want to thank you for making this tool available, unfortunately when i try to run i get following error : 

```
Error: Unable to initialize main class gui.MainFrame
Caused by: java.lang.NoClassDefFoundError: jssc/SerialPortEventListener
```

I am not familar with java in general so any help would be appreciated.

**Comment by iordic** [comment]
Hi w1nsid! Thank you for notify the issue. The jar was packed without including dependencies. I modified the configuration *pom.xml* file and build it again. Now should work, the file is here: [jar with dependencies](https://github.com/iordic/jdcx/raw/main/target/jdcx-jar-with-dependencies.jar)

Anyway it can have some bugs. For example, sometimes you have to click on connect button more than once.
